theme: jekyll-theme-minimal
color-scheme: auto
title: Zhen Guo (国振)
description: PhD student at MIT EECS
logo: profile.jpeg
author:
  email:         zguo0525 AT mit.edu
  googlescholar: https://scholar.google.com/citations?user=P_cJy4MAAAAJ&hl=en
  github:        zguo0525
  linkedin:      zhen-guo-b764b6b4
