theme: jekyll-theme-minimal
title: Gavin Guo (国振)
description: AI researcher at Meta Superintelligence Labs. Previously Apple Siri, MIT-IBM Watson, MIT.
logo: profile.jpeg
author:
  email:         zguo0525@berkeley.edu
  googlescholar: https://scholar.google.com/citations?user=P_cJy4MAAAAJ&hl=en
  github:        zguo0525
  linkedin:      gavin-guo-b764b6b4/
  twitter:       Zhen4good

exclude:
  - new_design
  - README.md
  - "*.tex"
  - "*.aux"
  - "*.log"
  - "*.fls"
  - "*.fdb_latexmk"
  - "*.out"
  - resume.cls
