theme: jekyll-theme-minimal
title: Gavin Guo (国振)
description: AI researcher at Meta Superintelligence Labs. Previously Apple Siri, MIT-IBM Watson, MIT.
url: "https://zguo0525.github.io"
logo: profile.jpeg

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

collections:
  articles:
    output: true
    permalink: "/articles/:name:output_ext"

feed:
  collections:
    - articles
author:
  email:         zguo0525@berkeley.edu
  googlescholar: https://scholar.google.com/citations?user=P_cJy4MAAAAJ&hl=en
  github:        zguo0525
  linkedin:      gavin-guo-b764b6b4/
  twitter:       Zhen4good

defaults:
  - scope:
      path: ""
    values:
      image: /profile.jpeg

exclude:
  - README.md
  - group.png
  - neo.jpeg
  - assets/fonts
  - "*.tex"
  - "*.aux"
  - "*.log"
  - "*.fls"
  - "*.fdb_latexmk"
  - "*.out"
  - resume.cls
  - vendor
  - Gemfile
  - screenshots
  - "cv*.pdf"
  - Gemfile.lock
  - .bundle
  - node_modules
