theme: jekyll-theme-minimal
color-scheme: auto
title: Gavin Guo (国振)
description: Apple Intelligence, Siri
logo: profile.jpeg
author:
  email:         zguo0525 AT mit.edu
  googlescholar: https://scholar.google.com/citations?user=P_cJy4MAAAAJ&hl=en
  github:        zguo0525
  linkedin:      gavin-guo-b764b6b4/
  twitter:       Zhen4good
